# Generated by Django 4.0.5 on 2022-06-08 15:45

from django.db import migrations, models
import django.db.models.deletion
import hotel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomextra_name', models.CharField(max_length=50, verbose_name='Name of Extra')),
                ('roomextra_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cost')),
                ('roomextra_info1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Room Extra Info')),
                ('roomextra_info2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Room Extra Info 2')),
                ('roomextra_date1', models.DateTimeField(blank=True, null=True, verbose_name='Room Extra Date 1')),
                ('roomextra_date2', models.DateTimeField(blank=True, null=True, verbose_name='Room Extra Date 2')),
                ('roomextra_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'RoomExtra',
                'verbose_name_plural': 'RoomExtras',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype_name', models.CharField(max_length=50, verbose_name='Name')),
                ('roomtype_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cost of Room/Night')),
                ('roomtype_cost1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cost of Room/Night 1')),
                ('roomtype_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='RoomType Info 1')),
                ('roomtype_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'RoomType',
                'verbose_name_plural': 'RoomTypes',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.CharField(db_index=True, default=hotel.models.generateRoomNumber, max_length=50, unique=True, verbose_name='Room Number')),
                ('roomcapacity', models.PositiveIntegerField(verbose_name='Room Capacity')),
                ('roombed', models.PositiveIntegerField(verbose_name='Number of Beds')),
                ('roombath', models.PositiveIntegerField(verbose_name='Number of Bath')),
                ('roomdimension', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Dimension (in Square Feet)')),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
