# Generated by Django 4.0.5 on 2022-06-16 17:29

from django.db import migrations, models
import django.db.models.deletion
import hotel.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roomstatus', models.CharField(choices=[('cv', 'Clean Vacant'), ('co', 'Clean Occupied'), ('dv', 'Dirty Vacant'), ('do', 'Dirty Occupied')], default='dv', max_length=2, verbose_name='Room Status')),
                ('roomnumber', models.CharField(db_index=True, default=hotel.models.generateRoomNumber, max_length=50, unique=True, verbose_name='Room Number')),
                ('roomnumber_url', models.SlugField(null=True, verbose_name='Room Number URL')),
                ('roomcapacity', models.PositiveIntegerField(verbose_name='Room Capacity')),
                ('roombed', models.PositiveIntegerField(verbose_name='Number of Beds')),
                ('roombath', models.PositiveIntegerField(verbose_name='Number of Bath')),
                ('roomdimension', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Dimension (in Square Feet)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(verbose_name='Updated At')),
                ('is_available', models.BooleanField(default=True, verbose_name='Room Available')),
                ('roomdate', models.DateTimeField(blank=True, null=True, verbose_name='Empty Date Field')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomExtra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roomextra_name', models.CharField(max_length=50, verbose_name='Name of Extra')),
                ('roomextra_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cost')),
                ('roomextra_info1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Room Extra Info')),
                ('roomextra_info2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Room Extra Info 2')),
                ('roomextra_date1', models.DateTimeField(blank=True, null=True, verbose_name='Room Extra Date 1')),
                ('roomextra_date2', models.DateTimeField(blank=True, null=True, verbose_name='Room Extra Date 2')),
                ('roomextra_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'RoomExtra',
                'verbose_name_plural': 'RoomExtras',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roomtype_name', models.CharField(max_length=50, verbose_name='Name')),
                ('roomtype_cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cost of Room/Night')),
                ('roomtype_cost1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cost of Room/Night 1')),
                ('roomtype_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='RoomType Info 1')),
                ('roomtype_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'RoomType',
                'verbose_name_plural': 'RoomTypes',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roomimage_main', models.ImageField(upload_to=hotel.models.room_image_upload_handler, verbose_name='Main Room Image')),
                ('roomimage_1', models.ImageField(blank=True, null=True, upload_to=hotel.models.room_image_upload_handler, verbose_name='Room Image 1')),
                ('roomimage_2', models.ImageField(blank=True, null=True, upload_to=hotel.models.room_image_upload_handler, verbose_name='Room Image 2')),
                ('roomimage_3', models.ImageField(blank=True, null=True, upload_to=hotel.models.room_image_upload_handler, verbose_name='Room Image 3')),
                ('roomimage_4', models.ImageField(blank=True, null=True, upload_to=hotel.models.room_image_upload_handler, verbose_name='Room Image 4')),
                ('roomimage_5', models.ImageField(blank=True, null=True, upload_to=hotel.models.room_image_upload_handler, verbose_name='Room Image 5')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'RoomImage',
                'verbose_name_plural': 'RoomImages',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='roomextras',
            field=models.ManyToManyField(to='hotel.roomextra', verbose_name='List of Extra Items'),
        ),
        migrations.AddField(
            model_name='room',
            name='roomtype',
            field=models.ForeignKey(limit_choices_to={'roomtype_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.roomtype'),
        ),
    ]
