# Generated by Django 4.0.5 on 2022-06-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomimage', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Room Image')),
                ('roomimage1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Room Image')),
                ('roomimage2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Room Image')),
                ('roomimage3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Room Image')),
                ('roomimage4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Room Image')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='')),
            ],
            options={
                'verbose_name': 'RoomImage',
                'verbose_name_plural': 'RoomImages',
            },
        ),
    ]
