# Generated by Django 4.0.5 on 2022-06-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
