# Generated by Django 4.0.5 on 2022-06-17 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import reservation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingnumber', models.CharField(default=reservation.models.generateBookingNumber, max_length=120, verbose_name='Booking Number')),
                ('bookingstatus', models.CharField(choices=[('Cancel', 'Cancelled'), ('Checkedin', 'Checked In'), ('Unattended', 'Unattended'), ('Expired', '')], default='Unattended', max_length=50, verbose_name='Status')),
                ('bookingfrom', models.DateTimeField(default=django.utils.timezone.now, validators=[reservation.models.validate_bookingfrom], verbose_name='From')),
                ('bookingnights', models.PositiveIntegerField(default=1, verbose_name='Number of Nights')),
                ('bookingto', models.DateTimeField(blank=True, verbose_name='To')),
                ('bookingconfirm', models.BooleanField(blank=True, null=True, verbose_name='Booking Confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bookingcontent', models.TextField(blank=True, help_text='Add any extra Information here', null=True, verbose_name='Comment')),
                ('bookingby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('bookingroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-bookingfrom', 'bookingconfirm'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkinbooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'CheckIn',
                'verbose_name_plural': 'CheckIns',
            },
        ),
    ]
